export const enum KEYS {
  C = 'C',
  V = 'V',
  X = 'X',
  Z = 'Z',
  Y = 'Y',
  A = 'A',
  G = 'G',
  L = 'L',
  F = 'F',
  D = 'D',
  B = 'B',
  P = 'P',
  R = 'R',
  MINUS = '-',
  EQUAL = '=',
  DELETE = 'DELETE',
  UP = 'ARROWUP',
  DOWN = 'ARROWDOWN',
  LEFT = 'ARROWLEFT',
  RIGHT = 'ARROWRIGHT',
  ENTER = 'ENTER',
  SPACE = ' ',
  TAB = 'TAB',
  BACKSPACE = 'BACKSPACE',
  ESC = 'ESCAPE',
  PAGEUP = 'PAGEUP',
  PAGEDOWN = 'PAGEDOWN',
  F5 = 'F5',
}

export const HOTKEY_DOC = [
  {
    type: 'ทั่วไป',
    children: [
      { label: 'ตัด', value: 'Ctrl + X' },
      { label: 'คัดลอก', value: 'Ctrl + C' },
      { label: 'วาง', value: 'Ctrl + V' },
      { label: 'เลือกทั้งหมด', value: 'Ctrl + A' },
      { label: 'เลิกทำ', value: 'Ctrl + Z' },
      { label: 'ทำซ้ำ', value: 'Ctrl + Y' },
      { label: 'ลบ', value: 'Delete / Backspace' },
      { label: 'เลือกหลายรายการ', value: 'กด Ctrl หรือ Shift' },
      { label: 'พิมพ์', value: 'Ctrl + P' },
      { label: 'ปิด', value: 'ESC' },
    ],
  },
  {
    type: 'พรีวิวหน้า',
    children: [
      { label: 'พรีวิวจากหน้าแรก', value: 'F5' },
      { label: 'พรีวิวจากหน้าปัจจุบัน', value: 'Shift + F5' },
      { label: 'หน้าก่อน', value: '↑ / ← / PgUp' },
      { label: 'หน้าถัดไป', value: '↓ / → / PgDown' },
      { label: 'หน้าถัดไป', value: 'Enter / Space' },
      { label: 'ออกจากพรีวิว', value: 'ESC' },
    ],
  },
  {
    type: 'แก้ไขหน้า',
    children: [
      { label: 'หน้าใหม่', value: 'Enter' },
      { label: 'เลื่อนแคนวาส', value: 'Space + ลากเมาส์' },
      { label: 'ซูมแคนวาส', value: 'Ctrl + ล้อเมาส์' },
      { label: 'ซูมเข้า', value: 'Ctrl + =' },
      { label: 'ซูมออก', value: 'Ctrl + -' },
      { label: 'พอดีหน้าจอ', value: 'Ctrl + 0' },
      { label: 'หน้าก่อน (เมื่อไม่ได้เลือกวัตถุ)', value: '↑ / ←' },
      { label: 'หน้าถัดไป (เมื่อไม่ได้เลือกวัตถุ)', value: '↓ / →' },
      { label: 'หน้าก่อน', value: 'เลื่อนขึ้น / PgUp' },
      { label: 'หน้าถัดไป', value: 'เลื่อนลง / PgDown' },
    ],
  },
  {
    type: 'จัดการวัตถุ',
    children: [
      { label: 'เลื่อน', value: '↑ / ← / ↓ / →' },
      { label: 'ล็อก', value: 'Ctrl + L' },
      { label: 'จัดกลุ่ม', value: 'Ctrl + G' },
      { label: 'ยกเลิกกลุ่ม', value: 'Ctrl + Shift + G' },
      { label: 'นำมาหน้าสุด', value: 'Alt + F' },
      { label: 'ส่งไปหลังสุด', value: 'Alt + B' },
      { label: 'ล็อกอัตราส่วน', value: 'กด Ctrl หรือ Shift' },
      { label: 'สร้างเส้นแนวนอน / แนวตั้ง', value: 'กด Ctrl หรือ Shift' },
      { label: 'สลับโฟกัสวัตถุ', value: 'Tab' },
      { label: 'ยืนยันการครอปรูป', value: 'Enter' },
    ],
  },
  {
    type: 'แก้ไขตาราง',
    children: [
      { label: 'ไปเซลล์ถัดไป', value: 'Tab' },
      { label: 'แทรกแถวด้านบน', value: 'Ctrl + ↑' },
      { label: 'แทรกแถวด้านล่าง', value: 'Ctrl + ↓' },
      { label: 'แทรกคอลัมน์ซ้าย', value: 'Ctrl + ←' },
      { label: 'แทรกคอลัมน์ขวา', value: 'Ctrl + →' },
    ],
  },
  {
    type: 'แก้ไขข้อความ',
    children: [
      { label: 'ตัวหนา', value: 'Ctrl + B' },
      { label: 'ตัวเอียง', value: 'Ctrl + I' },
      { label: 'ขีดเส้นใต้', value: 'Ctrl + U' },
      { label: 'ขีดฆ่า', value: 'Ctrl + D' },
    ],
  },
]
